Glen.MVC2/Controllers/AttachmentController.cs
using System.Web.Mvc;
using BitMinistry.Common;
using Glen.Domain.Entities;
using Glen.MVC.Helpers;

namespace Glen.MVC.Controllers
{
    public class AttachmentController : BaseController
    {
        

        

        [GlenAuthorize]
        public ActionResult Retrive(int id)
        {
            id.ThrowIfArgumentNull(nameof(id));
            
            var stream = AttachmentFileRepo.Retrive(id);
            var att = NhSession.Get<Attachment>(id);

            return File(stream, "application/octet-stream", att.FileName );
        }

        [GlenAuthorize(Roles = "Boss,ProjectManager,Sales")]
        public ActionResult Delete( int id, int customerId)
        {
            id.ThrowIfArgumentNull(nameof(id));
            id.ThrowIfArgumentNull(nameof(customerId));

            NhSession.Delete(NhSession.Get<Attachment>(id));
            NhSession.Flush();
            AttachmentFileRepo.Delete(id);

            return RedirectToAction("Edit", "Customer", new { id = customerId });
        }


    }
}

Glen.MVC2/Controllers/CustomerController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using Glen.MVC.Helpers;
using System.Web.Mvc;
using Glen.Domain.Entities;

namespace Glen.MVC.Controllers
{
    public class CustomerController  : BaseController
    {
        
        
        [GlenAuthorize(Roles = "Sales,Boss")]
        public ActionResult Index()
        {
            return View("Index", CustomerService.All );
        }

        [GlenAuthorize(Roles = "Sales,ProjectManager,Boss")]
        public ActionResult Edit(int id)
        {
            var customer = CustomerService.Get( id);
            
            return View( "Edit", customer ?? new Customer() );
        }

        [HttpPost]
        [GlenAuthorize(Roles = "Sales,ProjectManager,Boss")]

        public ActionResult Edit(Customer customer)
        {

            CustomerService.SaveOrUpdate( customer );

            AddAttachments(customer);


            return Redirect("~/Customer/Edit/"+ customer.Id );
        }

        [GlenAuthorize(Roles = "Boss")]
        public ActionResult Delete(int id)
        {
            CustomerService.DeleteById(id);

            return Index();
        }




        [GlenAuthorize(Roles = "Boss,ProjectManager,Sales")]
        private void AddAttachments(Customer customer)
        {
            if (Request.Files.Count == 0) return;

            for (int xi = 0; xi < Request.Files.Count; xi++)
            {
                HttpPostedFileBase file = Request.Files[xi];
                if (!String.IsNullOrEmpty(file.FileName))
                    CustomerService.AddAttachment(customer, file.InputStream, file.FileName);
            }
        }

        public ActionResult AddPayment(int id, decimal amount, DateTime xwhen)
        {
            NhSession.SaveOrUpdate( new Payment()
            {
                Customer = new Customer() { Id = id , },
                Amount = amount,
                XWhen = xwhen
            });
            NhSession.Flush();
            return RedirectToAction("Edit", new {id});
        }

        public ActionResult RemovePayment(int id)
        {
            var pay = NhSession.Get<Payment>(id);
            NhSession.Delete(pay);
            NhSession.Flush();
            return RedirectToAction("Edit", new { id = pay.Customer.Id });
        }
    }
}

Glen.MVC2/Controllers/InstallationController.cs
using Glen.Domain.Entities;
using Glen.MVC.Helpers;
using Glen.MVC.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Glen.MVC.Controllers
{

    public class InstallationController : BaseController
    {


        [GlenAuthorize]
        public ActionResult Index(string id = "Inquiry")
        {

            var status = (Installation.StatusEnum)Enum.Parse(typeof(Installation.StatusEnum), id, true);

            return View("List" + (status > Installation.StatusEnum.Order ? "Final" : status.ToString()),
                InstallationService.Find(p => p.Status == status));


        }

        //
        [HttpPost]
        [GlenAuthorize(Roles = "Boss,ProjectManager,Sales")]
        public ActionResult Create(Installation installation)
        {
            installation.Id = 0;
            installation.InquiryDate = DateTime.Now;
            
            InstallationService.SaveOrUpdate( installation );
            
            return RedirectToAction("Edit", "Customer", new { id = installation.Customer.Id });
            
        }


        //
        [GlenAuthorize]
        public ActionResult Edit(int id)
        {
            var project = InstallationService.Get(id);
            if (project == null)
                throw new NullReferenceException("There is no such project");

   
            ViewBag.topMenu = project.Status.ToString();

            if (Login.Position == PositionEnum.Installer)
                ViewBag.readOnly = "disabled=true";

            return View("Edit", project);
        }


        //
        [HttpPost]
        [GlenAuthorize(Roles = "Boss,ProjectManager,Sales")]
        public ActionResult Edit(Installation installation)
        {

            InstallationService.SaveOrUpdate(installation);
            if (installation.InquiryDate == null)
            {
                installation.InquiryDate = DateTime.Now;
                InstallationService.SaveOrUpdate(installation);

            }

            return RedirectToAction("Edit", new {id = installation.Id});

        }



        [GlenAuthorize(Roles = "Boss,ProjectManager,Sales")]
        public ActionResult Search(string id)
        {
            var term = id.ToLower();
            var projects = InstallationService.All.Where(p => (p.Title + p.Customer.Name).ToLower().Contains(term)).ToList();

            var customers =
                CustomerService.All.Where(c => c.Attachments.Any(a => a.FileName.ToLower().Contains(term)) 
                                                ||
                                               (c.Name + c.Phone + c.Phone2 + c.Email).ToLower().Contains(term)
                                               ||
                                               (c.Address != null && c.Address.formatted_address.ToLower().Contains(term)));

            return View("ListSearchResults", new object[] { projects , customers });
        }

        //
        [GlenAuthorize(Roles = "Boss")]
        public ActionResult Delete(int id)
        {
            var project = InstallationService.Get(id);
            if (project == null)
                throw new NullReferenceException("There is no such project");

            var prjStatus = project.Status;
            InstallationService.Delete(project);

            return Redirect("~/Project/Index/" + prjStatus);
        }


        [GlenAuthorize]
        public ActionResult ForwardToNextStatus(int id)
        {
            InstallationService.ForwardToNextStatus(id);

            return RedirectToAction("Edit", new { id });
        }

        [GlenAuthorize]
        public ActionResult EventsForCalendar()
        {

            int colorLooper = 0;

            Func<string> colorFunc = () =>
            {
                if (colorLooper == Statics.Colors.Length)
                    colorLooper = 0;
                else
                    colorLooper++;
                return Statics.Colors[colorLooper];
            };

            var eventsLinq = InstallationService.Find(x => x.Status == Installation.StatusEnum.Order || x.Status == Installation.StatusEnum.InStock )
                .Select(x => new
                {
                    title = x.Title + ", " + x.Customer.Name,
                    start = $"{x.Start:yyyy-MM-dd}",
                    end = $"{x.Deadline:yyyy-MM-dd}",
                    color = colorFunc(),
                    allDay = true,
                    url = Url.Action("Edit", new { id = x.Id })
                });

            return Json(eventsLinq, JsonRequestBehavior.AllowGet);
        }

        [GlenAuthorize]
        public ActionResult Calendar()
        {
            return View();
        }

    

      
    }

}

Glen.MVC2/Views/Customer/Edit.cshtml
@model Customer

@{
    Layout = "~/Views/Layouts/LeftMenu/Empty.cshtml";
}

@if (ViewBag.Exception != null)
{
    @Html.Partial("Exception", (Exception)ViewBag.Exception)
}

<link href="~/Views/Customer/customer.min.css" rel="stylesheet"/>

<form id="mainForm" method="post" class="form-horizontal" enctype="multipart/form-data"
      data-bv-message="This value is not valid"
      data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
      data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
      data-bv-feedbackicons-validating="glyphicon glyphicon-refresh">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title pull-left">
                @(Model.Name ?? "Create new customer" )
            </h3>

            <div class="pull-right">
                <button class="btn btn-primary btn-sm" type="submit">
                    <span class="glyphicon glyphicon-ok margin-right-5"></span> Save
                </button>
                @if (Model.Id > 0)
            {
                if (Model.Installations.Count == 0)
                {
                        <a class="btn btn-warning  btn-sm" href="@Url.Action("Delete", "Customer", new {Model.Id})">
                            <span class="glyphicon glyphicon-remove margin-right-5"></span> Delete
                        </a>
                    }

                }
            </div>
            <div class=clearfix></div>


        </div>
        <div class="panel-body">


            <div class="col-md-6">

                <div class="form-group">
                    <label class="col-xs-4 control-label">Email</label>
                    <div class="col-xs-8">
                        <input class="form-control" name="email" type="email" value="@Model.Email" placeholder="Email" @ViewBag.readOnly
                               data-bv-emailaddress="true" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-xs-4 control-label">Name</label>
                    <div class="col-xs-8">
                        <input class="form-control" name="name" value="@Model.Name" placeholder="Name" @ViewBag.readOnly
                               data-bv-notempty="true" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-xs-4 control-label">Phone</label>
                    <div class="col-xs-8">
                        <input class="form-control" name="phone" value="@Model.Phone" placeholder="Phone" @ViewBag.readOnly
                               pattern="[0-9 +\-]{6,20}$" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-xs-4 control-label">Phone 2</label>
                    <div class="col-xs-8">
                        <input class="form-control" name="Phone2" value="@Model.Phone2" placeholder="Phone" @ViewBag.readOnly
                               pattern="[0-9 +\-]{6,20}$" />
                    </div>
                </div>



            </div>
            <div class="col-md-6">

                @Html.Partial("~/Views/Contact/_address.cshtml", Model.Address ?? new Address())


                @Html.Partial("_attachments", Model)


            </div>


        </div>
    </div>
</form>


@if (Model.Id > 0)
{
    @Html.Partial("_payments", Model)

    @Html.Partial("ListInstallations", Model.Installations )
}

@section scripts {
    <script>
        $(document).ready(function() {

            $('form').bootstrapValidator();

            $(".date").datepicker({
                dateFormat: "yy-mm-dd",
                showAnim: "slideDown"
            });

        });

    </script>
}

Glen.MVC2/Views/Customer/Index.cshtml
@using BitMinistry.Common
@using PagedList
@using PagedList.Mvc
@model IEnumerable<Customer>

@{
    Layout = "~/Views/Layouts/LeftMenu/Customer.cshtml";

    int pageSize = 15, 
        page = Cnv.CInt( Request["page"] ?? "1" );

    var list = Model.ToPagedList(page, pageSize);

}

<div class="panel panel-default">
    <div class="panel-body">

        <table class="table table-hover">
            <thead>
                <tr>
      
                    <th>
                        Name
                    </th>
                    <th>
                        Address
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Phone
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var customer in list)
                {
                    <tr >
                        <td>
                            <a href="@Url.Action("Edit", "Customer", new { customer.Id } )">@customer.Name</a>
                        </td>
                        <td>
                            @customer.Address.Line 
                        </td>                        
                        <td>
                            @customer.Email
                        </td>
                        <td>
                            @customer.Phone
                        </td>
                        <td>

                            <a class="btn btn-default btn-sm" href="@Url.Action("Edit", "Customer", new { Id= customer.Id } )">
                                <span class="glyphicon glyphicon-edit"
                                      data-toggle="tooltip" data-placement="left" title="Edit that customer"></span>
                            </a>
                            
                            


                        </td>
                    </tr>
                }

            </tbody>
        </table>




    </div>
</div>


@Html.PagedListPager(list, pg => Url.Action("Index", new { page = pg }))

Glen.MVC2/Views/Customer/ListInstallations.cshtml
@model IEnumerable<Installation>
@{
    var total = Model.Sum(x => x.Price);
}



<form method="post" class="form-horizontal" enctype="multipart/form-data"
      data-bv-message="This value is not valid"
      data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
      data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
      data-bv-feedbackicons-validating="glyphicon glyphicon-refresh" action="@Url.Action("Create", "Installation")">

    <input type="hidden" name="Customer.Id" value="@ViewContext.RouteData.Values["id"]">
    <div class="customer-installation-rows">

        <div class="irow">

            <div>
                Title
            </div>
            <div>
                Type
            </div>
            <div>
                Status
            </div>
            <div>
                Size
            </div>
            <div>
                Material
            </div>
            <div>
                Measure i.
            </div>
            <div class="">
                Price
            </div>


        </div>

        @foreach (var installation in Model)
            {
            <div class="@(installation.Status < Installation.StatusEnum.Installed && installation.Deadline < DateTime.Now ? "danger" : "" ) irow">
                <div class="title">
                    <a href="@Url.Action("Edit", "Installation", new {installation.Id})">@installation.Title</a>
                </div>
                <div class="desc">
                    @NotEmpty(installation.BlindType.ToString())
                    <small>type</small>
                </div>
                <div>
                    @switch (installation.Status)
                    {
                        case Installation.StatusEnum.Inquiry:
                            @(installation.InquiryDate?.ToString("dd-MM-yyyy") ?? "")
                            break;
                        case Installation.StatusEnum.Proposal:
                            @(installation.ProposalDate?.ToString("dd-MM-yyyy") ?? "")
                            break;
                        case Installation.StatusEnum.Order:
                            @(installation.OrderDate?.ToString("dd-MM-yyyy") ?? "")
                            break;
                        case Installation.StatusEnum.InStock:
                            @(installation.InStockDate?.ToString("dd-MM-yyyy") ?? "")
                            break;
                        case Installation.StatusEnum.Installed:
                            @(installation.InstalledDate?.ToString("dd-MM-yyyy") ?? "")
                            break;
                        case Installation.StatusEnum.Archived:
                            @(installation.ArchivedDate?.ToString("dd-MM-yyyy") ?? "")
                            break;
                    }
                    @installation.Status.ToString()
                    @if (installation.Status >= Installation.StatusEnum.Order && installation.Status < Installation.StatusEnum.Archived)
                    {
                        <a href="@Url.Action("ForwardToNextStatus", "Installation", new {installation.Id})" class="btn btn-success btn-xs">
                            <i class="fa fa-forward"></i>
                        </a>
                    }

                </div>
                <div class="desc">
                    @NotEmpty(installation.Size())
                    <small>size</small>
                </div>
                <div class="desc">
                    @NotEmpty(installation.Material)
                    <small>material</small>
                </div>
                <div class="desc">
                    @NotEmpty(installation.MeasureInstructions)
                    <small>measure i</small>
                </div>
                <div>
                    @NotEmpty(installation.Price.HasValue ? installation.Price.Value.ToString("C") : "" )
                </div>

            </div>
        }
        <div class="irow nu-row">
            <div class="form-group">
                <input class="form-control" name="Title" placeholder="Title" id="newInstallationTitle"
                       data-bv-stringlength-message="Has to be longer then 1 letter"
                       data-bv-stringlength-min="2"
                       data-bv-notempty="true"
                       data-bv-notempty-message="The title is required and cannot be empty" />
            </div>
            <div>
                @Html.Partial("~/Views/Installation/_selectBlindType.cshtml", new Installation())
            </div>
            <div>
                <button class="btn btn-primary" type="submit">
                    <span class="fa fa-plus"></span> add
                </button>
            </div>
        </div>
        <div class="irow">
            <div>
                Total
            </div>
            <div>
                @(total.HasValue ? total.Value.ToString("C") : "" )
            </div>
        </div>
    </div>




</form>

@functions{

    private HtmlString NotEmpty( string xs)
    {
        return new HtmlString(string.IsNullOrEmpty(xs) ? "-" : xs);
    }


}

Glen.MVC2/Views/Customer/_attachments.cshtml
@model Customer  
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            Attachments
        </h3>
        <span class="btn btn-default btn-file pull-right">
            Browse and add <input type="file" name="attachments" multiple>
        </span>
    </div>
    <div class="panel-body">
        <div class="col-sm-9" id="attachmentsList">
            @if (@Model.Attachments != null)
            {
                foreach ( var attachment in @Model.Attachments.Where( x=> x != null ) )
                {
                    <blockquote>
                        <a href="@Url.Action("Retrive", "Attachment", new { id = attachment.Id })">@attachment.FileName</a>
                        <a class="btn btn-default btn-xs pull-right"
                           href="@Url.Action("Delete", "Attachment",
                                     new {attachment.Id, customerId = Model.Id })">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </blockquote>
                }
            }
        </div>
    </div>
</div>




<script language="javascript">

    $(document).on('change', '.btn-file :file', function () {
        var input = $(this);
        var files = input.prop("files");
        var names = $.map(files, function (val) { return val.name; });
        $("#newAttachmentTemplate").tmpl(names).appendTo("#attachmentsList");
    });
</script>
<script id="newAttachmentTemplate" type="template">
    <blockquote>
        ${$data}
        <span class="label label-warning">Not saved</span>
    </blockquote>
</script>

Glen.MVC2/Views/Customer/_createInstallation.cshtml
@using Glen.MVC.Models
@model Customer
@{
    Layout = null;
}

<form method="post" class="form-horizontal" enctype="multipart/form-data"
      data-bv-message="This value is not valid"
      data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
      data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
      data-bv-feedbackicons-validating="glyphicon glyphicon-refresh" action="@Url.Action("Create", "Installation")">

    <input type="hidden" name="Customer.Id" value="@Model.Id">

    <div class="col-md-6">
        <div class="form-group ">
            <input class="form-control" name="Title" placeholder="Title" id="newInstallationTitle"
                   data-bv-stringlength-message="Has to be longer then 1 letter"
                   data-bv-stringlength-min="2"
                   data-bv-notempty="true"
                   data-bv-notempty-message="The title is required and cannot be empty"/>
        </div>
    </div>
    <div class="row">
        <button class="btn btn-primary center-block" type="submit">
            <span class="glyphicon glyphicon-ok margin-right-5"></span> Create
        </button>
    </div>
</form>

Glen.MVC2/Views/Customer/_forProject.cshtml
@model Customer 
<div class="panel panel-default ">
    <div class="panel-heading">
        <h3 class="panel-title">
            Customer
        </h3>
    </div>
    <div class="panel-body panel-tight">
        <div class="well well-sm col-sm-12">
            <a href="@Url.Action("Edit", "Customer", new { id = @Model.Id })">@Model.Name</a>
        </div>

        <div class="well well-sm col-sm-8" style="word-wrap: break-word;">
            <a href="mailto:@Model.Email" style="color:black; font-size:11px;">@Model.Email</a>
        </div>
        @if (!String.IsNullOrEmpty(Model.Phone))
        {
            <div class="well well-sm col-sm-4">
                @Model.Phone
            </div>
        }

    </div>
</div>

Glen.MVC2/Views/Customer/_payments.cshtml
@model Customer
@{
    var balance = Model.Payments.Sum(x => x.Amount) - Model.Installations.Sum(x => x.Price) ;
    }
<div class="panel panel-default payments">
    <div class="panel-heading">
        <h3 class="panel-title">
            Payments
            <strong>Total @Model.Payments.Sum( x=> x.Amount).ToString("C")</strong>

            @if (balance != 0)
            {
                <span class="pull-right text-danger">
                    Balance @balance
                </span>
            }
            else
            {
                <span class="pull-right text-success">
                    <i class="fa fa-check fa-2x"></i>
                </span>
            }
        </h3>
    </div>
    <div class="panel-body">
        <div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">
            @foreach (var payment in Model.Payments ?? new List<Payment>())
            {
                <span class="well well-sm ">
                    <strong>@payment.Amount.ToString("C") </strong>
                    <span class="text-muted small">
                        (@payment.XWhen.ToString("dd-MM-yyyy"))
                    </span>
                    <a href="@Url.Action("RemovePayment", new { payment.Id })">
                        <i class="fa fa-remove text-danger xs"></i> 
                    </a>
                </span>
            }
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            @using (Html.BeginForm("AddPayment", "Customer", FormMethod.Post, new { @class = "form-inline" }))
            {
                @Html.HiddenFor( x=> x.Id)
                <div class="input-group">
                    <input class="form-control input-sm" placeholder="100.00" name="Amount" required="required" min="1" value="@Math.Max( 0, -1* balance.Value )"/>
                    <span class="input-group-addon">£</span>
                    <input class="form-control input-sm date" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="XWhen" required="required" />
                    <span class="input-group-btn ">
                        <button class="btn btn-success btn-sm" type="submit">
                            <i class="fa fa-plus"></i>
                            </button>
                    </span>
                </div>
            }
        </div>
    </div>

</div>