Glen.MVC2/Controllers/CustomerController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using Glen.MVC.Helpers;
using System.Web.Mvc;
using Glen.Domain.Entities;

namespace Glen.MVC.Controllers
{
    public class CustomerController  : BaseController
    {
        
        
        [GlenAuthorize(Roles = "Sales,Boss")]
        public ActionResult Index()
        {
            return View("Index", CustomerService.All );
        }

        [GlenAuthorize(Roles = "Sales,ProjectManager,Boss")]
        public ActionResult Edit(int id)
        {
            var customer = CustomerService.Get( id);
            
            return View( "Edit", customer ?? new Customer() );
        }

        [HttpPost]
        [GlenAuthorize(Roles = "Sales,ProjectManager,Boss")]

        public ActionResult Edit(Customer customer)
        {

            CustomerService.SaveOrUpdate( customer );

            AddAttachments(customer);


            return Redirect("~/Customer/Edit/"+ customer.Id );
        }

        [GlenAuthorize(Roles = "Boss")]
        public ActionResult Delete(int id)
        {
            CustomerService.DeleteById(id);

            return Index();
        }




        [GlenAuthorize(Roles = "Boss,ProjectManager,Sales")]
        private void AddAttachments(Customer customer)
        {
            if (Request.Files.Count == 0) return;

            for (int xi = 0; xi < Request.Files.Count; xi++)
            {
                HttpPostedFileBase file = Request.Files[xi];
                if (!String.IsNullOrEmpty(file.FileName))
                    CustomerService.AddAttachment(customer, file.InputStream, file.FileName);
            }
        }

        public ActionResult AddPayment(int id, decimal amount, DateTime xwhen)
        {
            NhSession.SaveOrUpdate( new Payment()
            {
                Customer = new Customer() { Id = id , },
                Amount = amount,
                XWhen = xwhen
            });
            NhSession.Flush();
            return RedirectToAction("Edit", new {id});
        }

        public ActionResult RemovePayment(int id)
        {
            var pay = NhSession.Get<Payment>(id);
            NhSession.Delete(pay);
            NhSession.Flush();
            return RedirectToAction("Edit", new { id = pay.Customer.Id });
        }
    }
}

Glen.MVC2/Controllers/EmployeeController.cs
using System.Linq;
using System.Web.Mvc;
using BitMinistry.Common;
using Glen.Domain.Entities;
using Glen.MVC.Helpers;
using Glen.MVC.Models;


namespace Glen.MVC.Controllers
{
    
    public class EmployeeController : BaseController
    {
        

        
        [GlenAuthorize(Roles=("Boss"))]
        public ActionResult Index()
        {
            return View("Index", EmployeeRepository.All);
        }

        [GlenAuthorize]
        public ActionResult Edit(int id)
        {
            var employee = EmployeeRepository.Get(id);
            
            return View("Edit", employee ?? new Employee());
        }

        [HttpPost]
        [GlenAuthorize]
        public ActionResult Edit(Employee employee)
        {

            EmployeeRepository.SaveOrUpdate( employee );

            return Redirect("~/Employee/Edit/" + employee.Id);
            
        }

        [GlenAuthorize(Roles="Boss")]
        public ActionResult Delete(int id)
        {
            EmployeeRepository.DeleteById(id);

            return Index();
        }

        public ActionResult LogIn()
        {
            var rememberMe = LoginRepo.Find(l => l.IpAddress == Request.UserHostAddress ).FirstOrDefault();
            var model = new LoginViewModel(); 
            if (rememberMe != null)
            {
                if (rememberMe.KeepMeLoggedIn)
                    return DoLogin(rememberMe.Employee);
                
                model.Employee = rememberMe.Employee;
            }

            return View( model );
        }
        private ActionResult DoLogin(Employee employee)
        {
            Employee login = null;
            employee.InjectInto(ref login);

            Session["Login"] = login;

            if (Request["returnUrl"] != null)
                return new RedirectResult(Request["returnUrl"]);

            return RedirectToAction("Index", "Installation");
        }

        [HttpPost]
        public ActionResult LogIn(LoginViewModel model)
        {
            var incomingEmployee = EmployeeRepository.Find(e => e.Email == model.Email).FirstOrDefault();

            if (incomingEmployee == null )
            {
                model.ErrorMessage = "No such user";
                return View(model);
            }

            if (model.PasswordReminder)
            {
//                KMail.Send(ConfigurationManager.AppSettings["SystemEmail"] ?? model.Email, model.Email, login.Password, "password reminder");
                model.ErrorMessage = "Password is sent to "+ model.Email;
                return View(model);
            }

            if (incomingEmployee.Password != model.Password )
            {
                model.ErrorMessage = "Incorrect password";
                return View(model);
            }
            if (model.KeepMeLoggedIn)
            {
                var saved = LoginRepo.Find(l => l.IpAddress == Request.UserHostAddress).FirstOrDefault();
                if (saved != null)
                {
                    saved.Employee = incomingEmployee;
                    saved.KeepMeLoggedIn = model.KeepMeLoggedIn;
                }
                else
                    saved = new Login()
                    {
                        Employee = incomingEmployee,
                        IpAddress = Request.UserHostAddress, 
                        KeepMeLoggedIn = model.KeepMeLoggedIn
                    };

                LoginRepo.SaveOrUpdate(saved);
            }
            return DoLogin( incomingEmployee );
        }

        public ActionResult LogOff()
        {
            Session["Login"] = null;

            var rememberMe = LoginRepo.Find(l => l.IpAddress == Request.UserHostAddress ).FirstOrDefault();

            if (rememberMe != null)
                if (rememberMe.KeepMeLoggedIn)
                {
                    rememberMe.KeepMeLoggedIn = false; 
                    LoginRepo.SaveOrUpdate( rememberMe );
                }

            return RedirectToAction("Index", "Installation");
        }



    }
}

Glen.MVC2/Views/Layouts/LeftMenu/Customer.cshtml
@{
    Layout = "~/Views/Layouts/_default.cshtml";
    ViewBag.action = Request.RequestContext.RouteData.Values["Action"];
}
<div class="row clearfix">
    <div class="col-md-2">
        <h4>
            Customers
        </h4>
        <div class="list-group">

            @if (LoginRole.Is(PositionEnum.Sales))
            {

                <a href="@Url.Action("Index", "Customer")" class="list-group-item  @Html.Raw(ViewBag.action == "Index" ? "active" : "")">
                    <span class="glyphicon glyphicon-list margin-right-5"></span>
                    List
                </a>
                <a href="@Url.Action("Edit", "Customer", new {Id = 0})" class="list-group-item  @Html.Raw(ViewBag.action == "Edit" ? "active" : "")">
                    <span class="glyphicon glyphicon-plus margin-right-5"></span>
                    New customer
                </a>
            }

        </div>


        <p class="text-info" style="padding: 5px;">
            Manage your customers.
        </p>
        <p class="text-info" style="padding: 5px;">
            Create project for a customer.
        </p>



    </div>
    <div class="col-md-10">
        @RenderBody()
    </div>
</div>

@RenderSection("scripts", required: false)
@RenderSection("css", required: false)

Glen.MVC2/Views/Layouts/LeftMenu/Employee.cshtml
@{
    Layout = "~/Views/Layouts/_default.cshtml"; 
    ViewBag.action = Request.RequestContext.RouteData.Values["Action"]; 
}

<div class="row clearfix">
    <div class="col-md-2">
        <div class="list-group">
@if (LoginRole.Is())
{
    <a href="@Url.Action("Index", "Employee")" class="list-group-item  @Html.Raw( ViewBag.action =="Index" ? "active" : "" )">
        <span class="glyphicon glyphicon-list margin-right-5"></span>
        List
    </a>

    <a href="@Url.Action("Edit", "Employee", new {Id = "create_new"})" class="list-group-item ">
        <span class="glyphicon glyphicon-plus margin-right-5"></span>
        New employee
    </a>

}
        </div>


        <p class="text-info" style="padding: 5px;">
            Everything related to employees
        </p>
        

    </div>
    <div class="col-md-10">
        @RenderBody()
    </div>
</div>
@RenderSection("scripts", required: false)
@RenderSection("css", required: false)

Glen.MVC2/Views/Layouts/LeftMenu/Empty.cshtml
@{
    Layout = "~/Views/Layouts/_default.cshtml"; 
}

<div class="row clearfix">
    <div class="col-md-12">
        @RenderBody()
    </div>
</div>
@RenderSection("scripts", required: false)
@RenderSection("css", required: false)

Glen.MVC2/Views/Layouts/LeftMenu/Inquiry.cshtml
@using Glen.MVC.Helpers
@{
    Layout = "~/Views/Layouts/_default.cshtml";
    ViewBag.action = Request.RequestContext.RouteData.Values["Action"];
}

<div class="row clearfix">
    <div class="col-md-2">
        <div class="list-group">

            @if (LoginRole.Is(PositionEnum.Sales))
            {

                <a href="@Url.Action("Index", "Project", new { id = "Inquiry" })" class="list-group-item @Html.Raw( ViewBag.action =="Index" ? "active" : "" )">
                    <span class="glyphicon glyphicon-list margin-right-5"></span>
                    List
                </a>

                <a href="@Url.Action("Index", "Customer")" class="list-group-item  @Html.Raw( ViewBag.action =="Create" ? "active" : "" )">
                    <span class="glyphicon glyphicon-plus margin-right-5"></span>
                    create new
                </a>
            }


        </div>
        
        <p class="text-info" style="padding: 5px;">
            Manage inquiries
        </p>

        <p class="text-info" style="padding: 5px;">
            Select customer to initiate a new project.
        </p>


    </div>
    <div class="col-md-10">
        @RenderBody()
    </div>
</div>

@RenderSection("scripts", required: false)

@RenderSection("css", required: false)

Glen.MVC2/Views/Layouts/LeftMenu/Order.cshtml
@{
    Layout = "~/Views/Layouts/_default.cshtml";
    ViewBag.topMenu = "Project";
    ViewBag.action = Request.RequestContext.RouteData.Values["Action"]; 
}

<div class="row clearfix">
    <div class="col-md-2">
        <div class="list-group">
            <a href="@Url.Action("Calendar", "Installation")" class="list-group-item @Html.Raw( ViewBag.action =="Calendar" ? "active" : "" )">
                <span class="glyphicon glyphicon-calendar margin-right-5"></span>
                Calendar
            </a>
            <a href="@Url.Action("Index", "Installation", new { id = "Order" })" class="list-group-item @Html.Raw( ViewBag.action =="Index" ? "active" : "" )">
                <span class="glyphicon glyphicon-list margin-right-5"></span>
                List
            </a>

        </div>


        <p class="text-info" style="padding: 5px;">
            Manage project data
        </p>
        

    </div>
    <div class="col-md-10">
        @RenderBody()
    </div>
</div>

@RenderSection("scripts", required: false)
@RenderSection("css", required: false)